[project]
name = "reaper-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ariel Grillo", email = "arielgrillo@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "mcp>=2.0.0",
]

[project.scripts]
reaper-mcp = "reaper_mcp:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
